window.SL_CATALOG = (function () {

  var film = [
    { id:"film_vertigo_1958", title:"Vertigo", type:"Film", year:1958 },
    { id:"film_psycho_1960", title:"Psycho", type:"Film", year:1960 },
    { id:"film_jaws_1975", title:"Jaws", type:"Film", year:1975 },
    { id:"film_star_wars_1977", title:"Star Wars", type:"Film", year:1977 },
    { id:"film_godfather_1972", title:"The Godfather", type:"Film", year:1972 },
    { id:"film_godfather_2_1974", title:"The Godfather Part II", type:"Film", year:1974 },
    { id:"film_raiders_1981", title:"Raiders of the Lost Ark", type:"Film", year:1981 },
    { id:"film_et_1982", title:"E.T. the Extra-Terrestrial", type:"Film", year:1982 },
    { id:"film_back_future_1985", title:"Back to the Future", type:"Film", year:1985 },
    { id:"film_breakfast_club_1985", title:"The Breakfast Club", type:"Film", year:1985 },
    { id:"film_die_hard_1988", title:"Die Hard", type:"Film", year:1988 },
    { id:"film_ferris_bueller_1986", title:"Ferris Bueller’s Day Off", type:"Film", year:1986 },
    { id:"film_terminator_2_1991", title:"Terminator 2: Judgment Day", type:"Film", year:1991 },
    { id:"film_jurassic_park_1993", title:"Jurassic Park (Film)", type:"Film", year:1993 },
    { id:"film_pulp_fiction_1994", title:"Pulp Fiction", type:"Film", year:1994 },
    { id:"film_forrest_gump_1994", title:"Forrest Gump", type:"Film", year:1994 },
    { id:"film_fight_club_1999", title:"Fight Club", type:"Film", year:1999 },
    { id:"film_matrix_1999", title:"The Matrix", type:"Film", year:1999 },
    { id:"film_sixth_sense_1999", title:"The Sixth Sense", type:"Film", year:1999 },
    { id:"film_gladiator_2000", title:"Gladiator", type:"Film", year:2000 },
    { id:"film_lotr_fellowship_2001", title:"The Lord of the Rings: The Fellowship of the Ring", type:"Film", year:2001 },
    { id:"film_lotr_two_towers_2002", title:"The Lord of the Rings: The Two Towers", type:"Film", year:2002 },
    { id:"film_lotr_return_2003", title:"The Lord of the Rings: The Return of the King", type:"Film", year:2003 },
    { id:"film_dark_knight_2008", title:"The Dark Knight", type:"Film", year:2008 },
    { id:"film_avatar_2009", title:"Avatar", type:"Film", year:2009 },
    { id:"film_inception_2010", title:"Inception", type:"Film", year:2010 },
    { id:"film_social_network_2010", title:"The Social Network", type:"Film", year:2010 },
    { id:"film_interstellar_2014", title:"Interstellar", type:"Film", year:2014 },
    { id:"film_mad_max_fury_2015", title:"Mad Max: Fury Road", type:"Film", year:2015 },
    { id:"film_get_out_2017", title:"Get Out", type:"Film", year:2017 },
    { id:"film_parasite_2019", title:"Parasite", type:"Film", year:2019 },
    { id:"film_dune_2021", title:"Dune (Film)", type:"Film", year:2021 },
    { id:"film_top_gun_maverick_2022", title:"Top Gun: Maverick", type:"Film", year:2022 }
  ];

  var tv = [
    { id:"tv_i_love_lucy_1951", title:"I Love Lucy", type:"TV", year:1951 },
    { id:"tv_twilight_zone_1959", title:"The Twilight Zone", type:"TV", year:1959 },
    { id:"tv_mash_1972", title:"M*A*S*H", type:"TV", year:1972 },
    { id:"tv_cheers_1982", title:"Cheers", type:"TV", year:1982 },
    { id:"tv_seinfeld_1989", title:"Seinfeld", type:"TV", year:1989 },
    { id:"tv_friends_1994", title:"Friends", type:"TV", year:1994 },
    { id:"tv_x_files_1993", title:"The X-Files", type:"TV", year:1993 },
    { id:"tv_sopranos_1999", title:"The Sopranos", type:"TV", year:1999 },
    { id:"tv_west_wing_1999", title:"The West Wing", type:"TV", year:1999 },
    { id:"tv_lost_2004", title:"Lost", type:"TV", year:2004 },
    { id:"tv_office_us_2005", title:"The Office (US)", type:"TV", year:2005 },
    { id:"tv_grey_anatomy_2005", title:"Grey’s Anatomy", type:"TV", year:2005 },
    { id:"tv_breaking_bad_2008", title:"Breaking Bad", type:"TV", year:2008 },
    { id:"tv_mad_men_2007", title:"Mad Men", type:"TV", year:2007 },
    { id:"tv_game_thrones_2011", title:"Game of Thrones", type:"TV", year:2011 },
    { id:"tv_walking_dead_2010", title:"The Walking Dead", type:"TV", year:2010 },
    { id:"tv_stranger_things_2016", title:"Stranger Things", type:"TV", year:2016 },
    { id:"tv_handmaids_tale_2017", title:"The Handmaid’s Tale", type:"TV", year:2017 },
    { id:"tv_succession_2018", title:"Succession", type:"TV", year:2018 },
    { id:"tv_last_of_us_2023", title:"The Last of Us", type:"TV", year:2023 }
  ];

  var book = [
    { id:"book_1984_orwell_1949", title:"1984", type:"Book", year:1949 },
    { id:"book_catcher_rye_1951", title:"The Catcher in the Rye", type:"Book", year:1951 },
    { id:"book_lord_flies_1954", title:"Lord of the Flies", type:"Book", year:1954 },
    { id:"book_hobbit_1937", title:"The Hobbit", type:"Book", year:1937 },
    { id:"book_to_kill_mockingbird_1960", title:"To Kill a Mockingbird", type:"Book", year:1960 },
    { id:"book_dune_1965", title:"Dune (Book)", type:"Book", year:1965 },
    { id:"book_godfather_1969", title:"The Godfather", type:"Book", year:1969 },
    { id:"book_shining_1977", title:"The Shining", type:"Book", year:1977 },
    { id:"book_hitchhiker_1979", title:"The Hitchhiker’s Guide to the Galaxy", type:"Book", year:1979 },
    { id:"book_handmaids_tale_1985", title:"The Handmaid’s Tale (Book)", type:"Book", year:1985 },
    { id:"book_it_1986", title:"It", type:"Book", year:1986 },
    { id:"book_harry_potter_1997", title:"Harry Potter and the Philosopher’s Stone", type:"Book", year:1997 },
    { id:"book_girl_dragon_tattoo_2005", title:"The Girl with the Dragon Tattoo", type:"Book", year:2005 },
    { id:"book_hunger_games_2008", title:"The Hunger Games", type:"Book", year:2008 },
    { id:"book_gone_girl_2012", title:"Gone Girl (Book)", type:"Book", year:2012 }
  ,
    { id:"film_clueless_1995", title:"Clueless", type:"Film", year:1995 },
    { id:"film_when_harry_met_sally_1989", title:"When Harry Met Sally", type:"Film", year:1989 },
    { id:"film_pretty_woman_1990", title:"Pretty Woman", type:"Film", year:1990 },
    { id:"film_notting_hill_1999", title:"Notting Hill", type:"Film", year:1999 },
    { id:"film_princess_bride_1987", title:"The Princess Bride", type:"Film", year:1987 },
    { id:"film_legally_blonde_2001", title:"Legally Blonde", type:"Film", year:2001 },
    { id:"film_mean_girls_2004", title:"Mean Girls", type:"Film", year:2004 },
    { id:"film_little_miss_sunshine_2006", title:"Little Miss Sunshine", type:"Film", year:2006 },
    { id:"film_pride_prejudice_2005", title:"Pride & Prejudice", type:"Film", year:2005 },
    { id:"film_lady_bird_2017", title:"Lady Bird", type:"Film", year:2017 },
    { id:"film_hidden_figures_2016", title:"Hidden Figures", type:"Film", year:2016 },
    { id:"film_a_star_is_born_2018", title:"A Star Is Born", type:"Film", year:2018 },
    { id:"film_barbie_2023", title:"Barbie", type:"Film", year:2023 },
    { id:"film_alien_1979", title:"Alien", type:"Film", year:1979 },
    { id:"film_blade_runner_1982", title:"Blade Runner", type:"Film", year:1982 },
    { id:"film_rocky_1976", title:"Rocky", type:"Film", year:1976 },
    { id:"film_titanic_1997", title:"Titanic", type:"Film", year:1997 },
    { id:"film_goodfellas_1990", title:"Goodfellas", type:"Film", year:1990 },
    { id:"film_big_lebowski_1998", title:"The Big Lebowski", type:"Film", year:1998 },
    { id:"film_whiplash_2014", title:"Whiplash", type:"Film", year:2014 },
    { id:"film_la_la_land_2016", title:"La La Land", type:"Film", year:2016 },
    { id:"tv_simpsons_1989", title:"The Simpsons", type:"TV", year:1989 },
    { id:"tv_frasier_1993", title:"Frasier", type:"TV", year:1993 },
    { id:"tv_buff_y_1997", title:"Buffy the Vampire Slayer", type:"TV", year:1997 },
    { id:"tv_sex_city_1998", title:"Sex and the City", type:"TV", year:1998 },
    { id:"tv_six_feet_under_2001", title:"Six Feet Under", type:"TV", year:2001 },
    { id:"tv_arrested_dev_2003", title:"Arrested Development", type:"TV", year:2003 },
    { id:"tv_black_mirror_2011", title:"Black Mirror", type:"TV", year:2011 },
    { id:"tv_crown_2016", title:"The Crown", type:"TV", year:2016 },
    { id:"book_foundation_1951", title:"Foundation", type:"Book", year:1951 },
    { id:"book_catch22_1961", title:"Catch-22", type:"Book", year:1961 },
    { id:"book_clockwork_orange_1962", title:"A Clockwork Orange", type:"Book", year:1962 },
    { id:"book_jurassic_park_1990", title:"Jurassic Park (Book)", type:"Book", year:1990 },
    { id:"book_game_thrones_1996", title:"A Game of Thrones", type:"Book", year:1996 },
    { id:"book_life_pi_2001", title:"Life of Pi", type:"Book", year:2001 },
    { id:"book_da_vinci_code_2003", title:"The Da Vinci Code", type:"Book", year:2003 },
    { id:"book_road_2006", title:"The Road", type:"Book", year:2006 },
    { id:"book_ready_player_one_2011", title:"Ready Player One", type:"Book", year:2011 }
,
    { id:"film_sound_of_music_1965", title:"The Sound of Music", type:"Film", year:1965 },
    { id:"film_mary_poppins_1964", title:"Mary Poppins", type:"Film", year:1964 },
    { id:"film_grease_1978", title:"Grease", type:"Film", year:1978 },
    { id:"film_terms_of_endearment_1983", title:"Terms of Endearment", type:"Film", year:1983 },
    { id:"film_kramer_vs_kramer_1979", title:"Kramer vs. Kramer", type:"Film", year:1979 },
    { id:"film_rain_man_1988", title:"Rain Man", type:"Film", year:1988 },
    { id:"film_sleepless_in_seattle_1993", title:"Sleepless in Seattle", type:"Film", year:1993 },
    { id:"film_youve_got_mail_1998", title:"You've Got Mail", type:"Film", year:1998 },
    { id:"film_love_actually_2003", title:"Love Actually", type:"Film", year:2003 },
    { id:"film_my_big_fat_greek_wedding_2002", title:"My Big Fat Greek Wedding", type:"Film", year:2002 },
    { id:"film_moonlight_2016", title:"Moonlight", type:"Film", year:2016 },
    { id:"film_little_women_2019", title:"Little Women", type:"Film", year:2019 },
    { id:"film_nomadland_2020", title:"Nomadland", type:"Film", year:2020 },
    { id:"film_everything_everywhere_2022", title:"Everything Everywhere All at Once", type:"Film", year:2022 },
    { id:"tv_golden_girls_1985", title:"The Golden Girls", type:"TV", year:1985 },
    { id:"tv_gilmore_girls_2000", title:"Gilmore Girls", type:"TV", year:2000 },
    { id:"tv_desperate_housewives_2004", title:"Desperate Housewives", type:"TV", year:2004 },
    { id:"tv_big_little_lies_2017", title:"Big Little Lies (TV)", type:"TV", year:2017 },
    { id:"tv_this_is_us_2016", title:"This Is Us", type:"TV", year:2016 },
    { id:"tv_the_good_place_2016", title:"The Good Place", type:"TV", year:2016 },
    { id:"tv_the_white_lotus_2021", title:"The White Lotus", type:"TV", year:2021 },
    { id:"tv_the_marvelous_mrs_maisel_2017", title:"The Marvelous Mrs. Maisel", type:"TV", year:2017 },
    { id:"book_eat_pray_love_2006", title:"Eat, Pray, Love", type:"Book", year:2006 },
    { id:"book_where_crawdads_sing_2018", title:"Where the Crawdads Sing", type:"Book", year:2018 },
    { id:"book_little_fires_everywhere_2017", title:"Little Fires Everywhere", type:"Book", year:2017 },
    { id:"book_big_little_lies_2014", title:"Big Little Lies (Book)", type:"Book", year:2014 },
    { id:"book_normal_people_2018", title:"Normal People (Book)", type:"Book", year:2018 },
    { id:"book_circe_2018", title:"Circe", type:"Book", year:2018 },
    { id:"book_song_of_achilles_2011", title:"The Song of Achilles", type:"Book", year:2011 }
,
    { id:"film_west_side_story_1961", title:"West Side Story", type:"Film", year:1961 },
    { id:"film_fiddler_roof_1971", title:"Fiddler on the Roof", type:"Film", year:1971 },
    { id:"film_annie_hall_1977", title:"Annie Hall", type:"Film", year:1977 },
    { id:"film_the_color_purple_1985", title:"The Color Purple", type:"Film", year:1985 },
    { id:"film_working_girl_1988", title:"Working Girl", type:"Film", year:1988 },
    { id:"film_dead_poets_society_1989", title:"Dead Poets Society", type:"Film", year:1989 },
    { id:"film_fried_green_tomatoes_1991", title:"Fried Green Tomatoes", type:"Film", year:1991 },
    { id:"film_four_weddings_funeral_1994", title:"Four Weddings and a Funeral", type:"Film", year:1994 },
    { id:"film_the_english_patient_1996", title:"The English Patient", type:"Film", year:1996 },
    { id:"film_as_good_as_it_gets_1997", title:"As Good as It Gets", type:"Film", year:1997 },
    { id:"film_chocolat_2000", title:"Chocolat", type:"Film", year:2000 },
    { id:"film_billy_elliot_2000", title:"Billy Elliot", type:"Film", year:2000 },
    { id:"film_the_hours_2002", title:"The Hours", type:"Film", year:2002 },
    { id:"film_eternal_sunshine_2004", title:"Eternal Sunshine of the Spotless Mind", type:"Film", year:2004 },
    { id:"film_the_piano_1993", title:"The Piano", type:"Film", year:1993 },
    { id:"film_juno_2007", title:"Juno", type:"Film", year:2007 },
    { id:"film_the_reader_2008", title:"The Reader", type:"Film", year:2008 },
    { id:"film_black_swan_2010", title:"Black Swan", type:"Film", year:2010 },
    { id:"film_the_shape_of_water_2017", title:"The Shape of Water", type:"Film", year:2017 },
    { id:"film_coda_2021", title:"CODA", type:"Film", year:2021 },
    { id:"tv_the_nanny_1993", title:"The Nanny", type:"TV", year:1993 },
    { id:"tv_felicity_1998", title:"Felicity", type:"TV", year:1998 },
    { id:"tv_veronica_mars_2004", title:"Veronica Mars", type:"TV", year:2004 },
    { id:"tv_scandal_2012", title:"Scandal", type:"TV", year:2012 },
    { id:"tv_the_americans_2013", title:"The Americans", type:"TV", year:2013 },
    { id:"tv_outlander_2014", title:"Outlander", type:"TV", year:2014 },
    { id:"tv_shameless_2011", title:"Shameless", type:"TV", year:2011 },
    { id:"tv_normal_people_2020", title:"Normal People (TV)", type:"TV", year:2020 },
    { id:"tv_and_just_like_that_2021", title:"And Just Like That...", type:"TV", year:2021 },
    { id:"book_bridges_madison_county_1992", title:"The Bridges of Madison County", type:"Book", year:1992 },
    { id:"book_secret_life_bees_2001", title:"The Secret Life of Bees", type:"Book", year:2001 },
    { id:"book_time_travelers_wife_2003", title:"The Time Traveler's Wife", type:"Book", year:2003 },
    { id:"book_kite_runner_2003", title:"The Kite Runner", type:"Book", year:2003 },
    { id:"book_lovely_bones_2002", title:"The Lovely Bones", type:"Book", year:2002 },
    { id:"book_help_2009", title:"The Help", type:"Book", year:2009 },
    { id:"book_goldfinch_2013", title:"The Goldfinch", type:"Book", year:2013 },
    { id:"book_station_eleven_2014", title:"Station Eleven", type:"Book", year:2014 },
    { id:"book_night_circus_2011", title:"The Night Circus", type:"Book", year:2011 }
];

  var recentFilm = [
    { id:"film_arrival_2016", title:"Arrival", type:"Film", year:2016 },
    { id:"film_manchester_by_the_sea_2016", title:"Manchester by the Sea", type:"Film", year:2016 },
    { id:"film_the_handmaiden_2016", title:"The Handmaiden", type:"Film", year:2016 },
    { id:"film_your_name_2016", title:"Your Name", type:"Film", year:2016 },
    { id:"film_blade_runner_2049_2017", title:"Blade Runner 2049", type:"Film", year:2017 },
    { id:"film_call_me_by_your_name_2017", title:"Call Me by Your Name", type:"Film", year:2017 },
    { id:"film_coco_2017", title:"Coco", type:"Film", year:2017 },
    { id:"film_phantom_thread_2017", title:"Phantom Thread", type:"Film", year:2017 },
    { id:"film_florida_project_2017", title:"The Florida Project", type:"Film", year:2017 },
    { id:"film_annihilation_2018", title:"Annihilation", type:"Film", year:2018 },
    { id:"film_hereditary_2018", title:"Hereditary", type:"Film", year:2018 },
    { id:"film_roma_2018", title:"Roma", type:"Film", year:2018 },
    { id:"film_spiderman_into_spiderverse_2018", title:"Spider-Man: Into the Spider-Verse", type:"Film", year:2018 },
    { id:"film_burning_2018", title:"Burning", type:"Film", year:2018 },
    { id:"film_knives_out_2019", title:"Knives Out", type:"Film", year:2019 },
    { id:"film_midsommar_2019", title:"Midsommar", type:"Film", year:2019 },
    { id:"film_portrait_lady_on_fire_2019", title:"Portrait of a Lady on Fire", type:"Film", year:2019 },
    { id:"film_1917_2019", title:"1917", type:"Film", year:2019 },
    { id:"film_uncut_gems_2019", title:"Uncut Gems", type:"Film", year:2019 },
    { id:"film_sound_of_metal_2019", title:"Sound of Metal", type:"Film", year:2019 },
    { id:"film_minari_2020", title:"Minari", type:"Film", year:2020 },
    { id:"film_the_father_2020", title:"The Father", type:"Film", year:2020 },
    { id:"film_promising_young_woman_2020", title:"Promising Young Woman", type:"Film", year:2020 },
    { id:"film_another_round_2020", title:"Another Round", type:"Film", year:2020 },
    { id:"film_drive_my_car_2021", title:"Drive My Car", type:"Film", year:2021 },
    { id:"film_worst_person_in_world_2021", title:"The Worst Person in the World", type:"Film", year:2021 },
    { id:"film_nope_2022", title:"Nope", type:"Film", year:2022 },
    { id:"film_tar_2022", title:"Tar", type:"Film", year:2022 },
    { id:"film_aftersun_2022", title:"Aftersun", type:"Film", year:2022 },
    { id:"film_rrr_2022", title:"RRR", type:"Film", year:2022 },
    { id:"film_the_batman_2022", title:"The Batman", type:"Film", year:2022 },
    { id:"film_past_lives_2023", title:"Past Lives", type:"Film", year:2023 },
    { id:"film_oppenheimer_2023", title:"Oppenheimer", type:"Film", year:2023 },
    { id:"film_killers_of_the_flower_moon_2023", title:"Killers of the Flower Moon", type:"Film", year:2023 },
    { id:"film_anatomy_of_a_fall_2023", title:"Anatomy of a Fall", type:"Film", year:2023 },
    { id:"film_zone_of_interest_2023", title:"The Zone of Interest", type:"Film", year:2023 },
    { id:"film_godzilla_minus_one_2023", title:"Godzilla Minus One", type:"Film", year:2023 },
    { id:"film_dune_part_two_2024", title:"Dune: Part Two", type:"Film", year:2024 },
    { id:"film_challengers_2024", title:"Challengers", type:"Film", year:2024 },
    { id:"film_furiosa_2024", title:"Furiosa: A Mad Max Saga", type:"Film", year:2024 },
    { id:"film_the_wild_robot_2024", title:"The Wild Robot", type:"Film", year:2024 },
    { id:"film_inside_out_2_2024", title:"Inside Out 2", type:"Film", year:2024 },
    { id:"film_wicked_2024", title:"Wicked", type:"Film", year:2024 },
    { id:"film_longlegs_2024", title:"Longlegs", type:"Film", year:2024 },
    { id:"film_mickey_17_2025", title:"Mickey 17", type:"Film", year:2025 }
  ];

  var recentTV = [
    { id:"tv_fleabag_2016", title:"Fleabag", type:"TV", year:2016 },
    { id:"tv_atlanta_2016", title:"Atlanta", type:"TV", year:2016 },
    { id:"tv_dark_2017", title:"Dark", type:"TV", year:2017 },
    { id:"tv_ozark_2017", title:"Ozark", type:"TV", year:2017 },
    { id:"tv_mindhunter_2017", title:"Mindhunter", type:"TV", year:2017 },
    { id:"tv_killing_eve_2018", title:"Killing Eve", type:"TV", year:2018 },
    { id:"tv_euphoria_2019", title:"Euphoria", type:"TV", year:2019 },
    { id:"tv_chernobyl_2019", title:"Chernobyl", type:"TV", year:2019 },
    { id:"tv_the_morning_show_2019", title:"The Morning Show", type:"TV", year:2019 },
    { id:"tv_the_boys_2019", title:"The Boys", type:"TV", year:2019 },
    { id:"tv_the_mandalorian_2019", title:"The Mandalorian", type:"TV", year:2019 },
    { id:"tv_ted_lasso_2020", title:"Ted Lasso", type:"TV", year:2020 },
    { id:"tv_the_queens_gambit_2020", title:"The Queen's Gambit", type:"TV", year:2020 },
    { id:"tv_i_may_destroy_you_2020", title:"I May Destroy You", type:"TV", year:2020 },
    { id:"tv_bridgerton_2020", title:"Bridgerton", type:"TV", year:2020 },
    { id:"tv_squid_game_2021", title:"Squid Game", type:"TV", year:2021 },
    { id:"tv_mare_of_easttown_2021", title:"Mare of Easttown", type:"TV", year:2021 },
    { id:"tv_only_murders_2021", title:"Only Murders in the Building", type:"TV", year:2021 },
    { id:"tv_abbott_elementary_2021", title:"Abbott Elementary", type:"TV", year:2021 },
    { id:"tv_yellowjackets_2021", title:"Yellowjackets", type:"TV", year:2021 },
    { id:"tv_station_eleven_2021", title:"Station Eleven", type:"TV", year:2021 },
    { id:"tv_arcane_2021", title:"Arcane", type:"TV", year:2021 },
    { id:"tv_severance_2022", title:"Severance", type:"TV", year:2022 },
    { id:"tv_the_bear_2022", title:"The Bear", type:"TV", year:2022 },
    { id:"tv_andor_2022", title:"Andor", type:"TV", year:2022 },
    { id:"tv_house_of_the_dragon_2022", title:"House of the Dragon", type:"TV", year:2022 },
    { id:"tv_slow_horses_2022", title:"Slow Horses", type:"TV", year:2022 },
    { id:"tv_the_rehearsal_2022", title:"The Rehearsal", type:"TV", year:2022 },
    { id:"tv_wednesday_2022", title:"Wednesday", type:"TV", year:2022 },
    { id:"tv_beef_2023", title:"Beef", type:"TV", year:2023 },
    { id:"tv_blue_eye_samurai_2023", title:"Blue Eye Samurai", type:"TV", year:2023 },
    { id:"tv_silo_2023", title:"Silo", type:"TV", year:2023 },
    { id:"tv_the_diplomat_2023", title:"The Diplomat", type:"TV", year:2023 },
    { id:"tv_one_piece_2023", title:"One Piece (Live Action)", type:"TV", year:2023 },
    { id:"tv_shogun_2024", title:"Shogun", type:"TV", year:2024 },
    { id:"tv_fallout_2024", title:"Fallout", type:"TV", year:2024 },
    { id:"tv_baby_reindeer_2024", title:"Baby Reindeer", type:"TV", year:2024 },
    { id:"tv_three_body_problem_2024", title:"3 Body Problem", type:"TV", year:2024 },
    { id:"tv_ripley_2024", title:"Ripley", type:"TV", year:2024 },
    { id:"tv_mr_and_mrs_smith_2024", title:"Mr. & Mrs. Smith", type:"TV", year:2024 },
    { id:"tv_true_detective_night_country_2024", title:"True Detective: Night Country", type:"TV", year:2024 },
    { id:"tv_presumed_innocent_2024", title:"Presumed Innocent", type:"TV", year:2024 },
    { id:"tv_the_penguin_2024", title:"The Penguin", type:"TV", year:2024 },
    { id:"tv_the_gentlemen_2024", title:"The Gentlemen", type:"TV", year:2024 }
  ];

  var recentBook = [
    { id:"book_pachinko_2017", title:"Pachinko", type:"Book", year:2017 },
    { id:"book_seven_husbands_2017", title:"The Seven Husbands of Evelyn Hugo", type:"Book", year:2017 },
    { id:"book_killers_of_flower_moon_2017", title:"Killers of the Flower Moon", type:"Book", year:2017 },
    { id:"book_the_power_2016", title:"The Power", type:"Book", year:2016 },
    { id:"book_the_hate_u_give_2017", title:"The Hate U Give", type:"Book", year:2017 },
    { id:"book_the_overstory_2018", title:"The Overstory", type:"Book", year:2018 },
    { id:"book_educated_2018", title:"Educated", type:"Book", year:2018 },
    { id:"book_becoming_2018", title:"Becoming", type:"Book", year:2018 },
    { id:"book_washington_black_2018", title:"Washington Black", type:"Book", year:2018 },
    { id:"book_the_silent_patient_2019", title:"The Silent Patient", type:"Book", year:2019 },
    { id:"book_the_dutch_house_2019", title:"The Dutch House", type:"Book", year:2019 },
    { id:"book_red_white_royal_blue_2019", title:"Red, White & Royal Blue", type:"Book", year:2019 },
    { id:"book_daisy_jones_2019", title:"Daisy Jones & The Six", type:"Book", year:2019 },
    { id:"book_priory_of_orange_tree_2019", title:"The Priory of the Orange Tree", type:"Book", year:2019 },
    { id:"book_the_testaments_2019", title:"The Testaments", type:"Book", year:2019 },
    { id:"book_mexican_gothic_2020", title:"Mexican Gothic", type:"Book", year:2020 },
    { id:"book_midnight_library_2020", title:"The Midnight Library", type:"Book", year:2020 },
    { id:"book_vanishing_half_2020", title:"The Vanishing Half", type:"Book", year:2020 },
    { id:"book_the_guest_list_2020", title:"The Guest List", type:"Book", year:2020 },
    { id:"book_piranesi_2020", title:"Piranesi", type:"Book", year:2020 },
    { id:"book_addie_larue_2020", title:"The Invisible Life of Addie LaRue", type:"Book", year:2020 },
    { id:"book_thursday_murder_club_2020", title:"The Thursday Murder Club", type:"Book", year:2020 },
    { id:"book_project_hail_mary_2021", title:"Project Hail Mary", type:"Book", year:2021 },
    { id:"book_klara_and_the_sun_2021", title:"Klara and the Sun", type:"Book", year:2021 },
    { id:"book_cloud_cuckoo_land_2021", title:"Cloud Cuckoo Land", type:"Book", year:2021 },
    { id:"book_empire_of_pain_2021", title:"Empire of Pain", type:"Book", year:2021 },
    { id:"book_crying_in_h_mart_2021", title:"Crying in H Mart", type:"Book", year:2021 },
    { id:"book_psalm_for_wild_built_2021", title:"A Psalm for the Wild-Built", type:"Book", year:2021 },
    { id:"book_house_of_sky_and_breath_2022", title:"House of Sky and Breath", type:"Book", year:2022 },
    { id:"book_tomorrow_and_tomorrow_2022", title:"Tomorrow, and Tomorrow, and Tomorrow", type:"Book", year:2022 },
    { id:"book_lessons_in_chemistry_2022", title:"Lessons in Chemistry", type:"Book", year:2022 },
    { id:"book_demon_copperhead_2022", title:"Demon Copperhead", type:"Book", year:2022 },
    { id:"book_babel_2022", title:"Babel", type:"Book", year:2022 },
    { id:"book_the_candy_house_2022", title:"The Candy House", type:"Book", year:2022 },
    { id:"book_sea_of_tranquility_2022", title:"Sea of Tranquility", type:"Book", year:2022 },
    { id:"book_book_lovers_2022", title:"Book Lovers", type:"Book", year:2022 },
    { id:"book_im_glad_my_mom_died_2022", title:"I'm Glad My Mom Died", type:"Book", year:2022 },
    { id:"book_legends_and_lattes_2022", title:"Legends & Lattes", type:"Book", year:2022 },
    { id:"book_chain_gang_all_stars_2023", title:"Chain-Gang All-Stars", type:"Book", year:2023 },
    { id:"book_yellowface_2023", title:"Yellowface", type:"Book", year:2023 },
    { id:"book_fourth_wing_2023", title:"Fourth Wing", type:"Book", year:2023 },
    { id:"book_iron_flame_2023", title:"Iron Flame", type:"Book", year:2023 },
    { id:"book_north_woods_2023", title:"North Woods", type:"Book", year:2023 },
    { id:"book_the_wager_2023", title:"The Wager", type:"Book", year:2023 },
    { id:"book_the_creative_act_2023", title:"The Creative Act", type:"Book", year:2023 },
    { id:"book_martyr_2024", title:"Martyr!", type:"Book", year:2024 },
    { id:"book_james_2024", title:"James", type:"Book", year:2024 },
    { id:"book_intermezzo_2024", title:"Intermezzo", type:"Book", year:2024 },
    { id:"book_ministry_of_time_2024", title:"The Ministry of Time", type:"Book", year:2024 },
    { id:"book_onyx_storm_2025", title:"Onyx Storm", type:"Book", year:2025 }
  ];

  return film
    .concat(tv)
    .concat(book)
    .concat(recentFilm)
    .concat(recentTV)
    .concat(recentBook);

})();
