// AUTO-GENERATED by tools/graph_build.sh
// Edit tools/graph_aliases.json for manual links; then rebuild.
window.SL_GRAPH_SEED = window.SL_GRAPH_SEED || {};
window.SL_GRAPH_SEED.edges = {
  "book_big_little_lies_2014": [
    "tv_big_little_lies_2017"
  ],
  "book_dune_1965": [
    "film_dune_2021"
  ],
  "book_godfather_1969": [
    "film_godfather_1972"
  ],
  "book_handmaids_tale_1985": [
    "tv_handmaids_tale_2017"
  ],
  "book_jurassic_park_1990": [
    "film_jurassic_park_1993"
  ],
  "book_normal_people_2018": [
    "tv_normal_people_2020"
  ],
  "film_dune_2021": [
    "book_dune_1965"
  ],
  "film_godfather_1972": [
    "book_godfather_1969"
  ],
  "film_jurassic_park_1993": [
    "book_jurassic_park_1990"
  ],
  "tv_big_little_lies_2017": [
    "book_big_little_lies_2014"
  ],
  "tv_handmaids_tale_2017": [
    "book_handmaids_tale_1985"
  ],
  "tv_normal_people_2020": [
    "book_normal_people_2018"
  ]
};
window.SL_GRAPH_SEED._meta = {
  "generatedAt": "2026-02-11T01:15:42.604Z",
  "catalogCount": 173,
  "nodeCount": 12,
  "directedEdgeCount": 12,
  "autoGroups": 1,
  "autoLinks": 2,
  "aliasLinks": 0,
  "removedUnknown": 0,
  "ambiguousKeys": 0
};
